wait for containers to start

diff --git a/.github/workflows/ci_4337.yml b/.github/workflows/ci_4337.yml
--- a/.github/workflows/ci_4337.yml
+++ b/.github/workflows/ci_4337.yml
@@ -37,6 +37,17 @@ jobs:
       - run: npm ci
       - run: |
           docker compose up -d
+          # wait for containers to start up
+          SECONDS=0
+          until curl -fs http://localhost:8545 >/dev/null && curl -fs http://localhost:3000 >/dev/null; do
+            if [[ $SECONDS -gt 30 ]]; then
+              echo "ERROR: timeout waiting for local node and bundler to start"
+              docker compose logs
+              exit 1
+            fi
+            sleep 1
+          done
+
           npm run test:e2e
   lint:
     runs-on: ubuntu-latest
