Implement E2E Test Using Reference Bundler (#155)
Fixes #145

This PR adds an E2E test that interacts with the reference bundler
implementation to ensure that the ERC-4337 module does not break any
rules during user operation validation.

In addition, some documentation on how to run the E2E tests was added as
well as a new CI step for executing the E2E tests.

diff --git a/.github/workflows/ci_4337.yml b/.github/workflows/ci_4337.yml
--- a/.github/workflows/ci_4337.yml
+++ b/.github/workflows/ci_4337.yml
@@ -14,14 +14,41 @@ jobs:
           node-version: 18.x
           cache: npm
           cache-dependency-path: 4337/package-lock.json
-      - run: npm ci 
-      - run: npm run build
+      - run: npm ci
+      - run: npm run build && npm run build:ts
       - run: npm run coverage
       - name: Coveralls
         uses: coverallsapp/github-action@master
         with:
           path-to-lcov: 4337/coverage/lcov.info
           github-token: ${{ secrets.GITHUB_TOKEN }}
+  e2e:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./4337
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+          cache: npm
+          cache-dependency-path: 4337/package-lock.json
+      - run: npm ci
+      - run: |
+          docker compose up -d
+          # wait for containers to start up
+          SECONDS=0
+          until curl -fs http://localhost:8545 >/dev/null && curl -fs http://localhost:3000 >/dev/null; do
+            if [[ $SECONDS -gt 30 ]]; then
+              echo "ERROR: timeout waiting for local node and bundler to start"
+              docker compose logs
+              exit 1
+            fi
+            sleep 1
+          done
+
+          npm run test:e2e
   lint:
     runs-on: ubuntu-latest
     defaults:
@@ -35,5 +62,5 @@ jobs:
           cache: npm
           cache-dependency-path: 4337/package-lock.json
       - run: npm ci
-      - run: npm run lint:sol
+      - run: npm run lint
       - run: npm run fmt:check
